
[font]
size = 10

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window.padding]
x = 16
y = 16

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[general]
live_config_reload = true
import = ["/home/jason/.config/alacritty/catppuccin-mocha.toml"]
